global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "admin"
    static_configs:
      - targets: ["casino-admin:8083"]
    metrics_path: "/metrics"

  - job_name: "auth"
    static_configs:
      - targets: ["casino-auth:8080"]
    metrics_path: "/metrics"

  - job_name: "payment"
    static_configs:
      - targets: ["casino-payment:8081"]
    metrics_path: "/metrics"

  - job_name: "cases"
    static_configs:
      - targets: ["casino-cases:8084"]
    metrics_path: "/metrics"

  - job_name: "inventory"
    static_configs:
      - targets: ["casino-inventory:8085"]
    metrics_path: "/metrics"

  - job_name: "gateway"
    static_configs:
      - targets: ["casino-gateway:8086"]
    metrics_path: "/metrics"
